export const ACTION_CONSTANT = {
    todolisthome:{
        GET_TODOLIST_START:'GET_TODOLIST_START',
        GET_TODOLIST_SUCCESS:'GET_TODOLIST_SUCCESS',
        GET_TODOLIST_FAILURE:'GET_TODOLIST_FAILURE',

        ADD_NEWTODO_START:'ADD_NEWTODO_START',
        ADD_NEWTODO_SUCCESS:'ADD_NEWTODO_SUCCESS',
        ADD_NEWTODO_FAILURE:'ADD_NEWTODO_FAILURE',

        UPDATE_NEWTODO_START:'UPDATE_NEWTODO_START',
        UPDATE_NEWTODO_SUCCESS:'UPDATE_NEWTODO_SUCCESS',
        UPDATE_NEWTODO_FAILURE:'UPDATE_NEWTODO_FAILURE',


        DELETE_NEWTODO_START:'DELETE_NEWTODO_START',
        DELETE_NEWTODO_SUCCESS:'DELETE_NEWTODO_SUCCESS',
        DELETE_NEWTODO_FAILURE:'DELETE_NEWTODO_FAILURE'
    }
}